modLoader="javafml"
loaderVersion="[34.1.0,)"
license="GNU General Public License 3"

[[mods]]
modId="petyourwolf"
version="1.2.1"
displayName="Pet Your Wolf"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/MiniMods/pet-your-wolf/update.json"
displayURL="https://mrcrayfish.com/minimods"
logoFile=""
credits="ItsBrenessa"
authors="MrCrayfish"
description="Allows the player to pet their tamed wolfs and heal them"

[[dependencies.petyourwolf]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.petyourwolf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.petyourwolf]]
    modId="obfuscate"
    mandatory=true
    versionRange="[0.5.0,)"
    ordering="AFTER"
    side="BOTH"