modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="petyourwolf"
version="1.2.0"
displayName="Pet Your Wolf"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/MiniMods/pet-your-wolf/update.json"
displayURL="https://mrcrayfish.com/minimods"
logoFile=""
credits="ItsBrenessa"
authors="MrCrayfish"
description="Allows the player to pet their tamed wolfs and heal them"

[[dependencies.petyourwolf]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.petyourwolf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.petyourwolf]]
    modId="obfuscate"
    mandatory=true
    versionRange="[0.3.3,)"
    ordering="AFTER"
    side="BOTH"